spring:
  profiles:
    active:
    - dev
---
server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml      # mybatis 配置所在路径
  type-aliases-package: com.frosty.springcloud.entity     # 所有entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml     # mapper映射文件
spring:
  profiles: dev
  application:
    name: springcloud-config-dept-client                       #对外暴露的微服务名 (在eureka内会显示其对外暴露名)
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource          # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver            # Mysql驱动包
    url: jdbc:mysql://localhost:3306/clouddb01            # 数据库名称
    username: root
    password: liuyan
    dbcp2:
      min-idle: 5                                         # 数据库连接池的最好维持连接数
      initial-size: 5                                     # 初始化链接数
      max-total: 5                                        # 最大链接数
      max-wait-millis: 200                                # 等待链接获取的最大超时时间
eureka:
  client:     #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:       #自定义erueka内 显示的微服务相对应的说明 (Status)
    instance-id: dept-client-8001
    prefer-ip-address: true       #访问路径显示IP地址
info:
  app.name: frosty-springcloud-test           #工程名
  company.name: www.springcloud.com           #公司名
  build.artifactId: $project.artifactId$      #获取具体哪个微服务的微服务名
  build.version: $project.version$            #版本号
---
server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml      # mybatis 配置所在路径
  type-aliases-package: com.frosty.springcloud.entity     # 所有entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml     # mapper映射文件
spring:
  profiles: test
  application:
    name: springcloud-config-dept-client                       #对外暴露的微服务名 (在eureka内会显示其对外暴露名)
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource          # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver            # Mysql驱动包
    url: jdbc:mysql://localhost:3306/clouddb02            # 数据库名称
    username: root
    password: liuyan
    dbcp2:
      min-idle: 5                                         # 数据库连接池的最好维持连接数
      initial-size: 5                                     # 初始化链接数
      max-total: 5                                        # 最大链接数
      max-wait-millis: 200                                # 等待链接获取的最大超时时间
eureka:
  client:     #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:       #自定义erueka内 显示的微服务相对应的说明 (Status)
    instance-id: dept-client-8001
    prefer-ip-address: true       #访问路径显示IP地址
info:
  app.name: frosty-springcloud-test           #工程名
  company.name: www.springcloud.com           #公司名
  build.artifactId: $project.artifactId$      #获取具体哪个微服务的微服务名
  build.version: $project.version$            #版本号